POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvdUB5b3UuY29tIiwiZXhwIjoxNzE3MDg4Nzk3LCJ1c2VySWQiOjR9.D2-Z4cwzNlGJFqTU4ogwYP3LrsF12t0nWGKosTj33ag

{
    "name":"Delete Me",
    "description":"Another Test Description",
    "location":"Location",
    "dateTime":"2023-11-29T07:00:00.000Z"
}
