POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1lQG1lLmNvbSIsImV4cCI6MTcxNjk5MzEyOCwidXNlcklkIjozfQ.N7aOkBJuhZLJQHFZpT82__9E3CpUXD462dkl5XMb3iQ

{
    "name":"Test Name 2",
    "description":"Test Description",
    "location":"Location",
    "dateTime":"2023-11-29T07:00:00.000Z"
}
