DELETE http://localhost:8080/events/7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlvdUB5b3UuY29tIiwiZXhwIjoxNzE3MDg4ODc5LCJ1c2VySWQiOjR9.-n7JZucDleEetyWBvKmkVFsHbGoWnFJ918oPvFx0QUM
